chore: update scripts folder

diff --git a/scripts/coverage b/scripts/coverage
--- a/scripts/coverage
+++ b/scripts/coverage
@@ -2,14 +2,19 @@
 
 set -eo pipefail
 
+if [[ ! -x "$(command -v go)" ]]; then
+  echo >&2 "go runtime is required: https://golang.org/doc/install"
+  echo >&2 "You can use scripts/go-wrapper $0 to use go in a docker container."
+  exit 1
+fi
+
 SOURCE_DIRECTORY=$(dirname "${BASH_SOURCE[0]}")
 cd "${SOURCE_DIRECTORY}/.."
-
 
 do_analyze() {
 
     mkdir -p testdata
-    go test -covermode=count -coverprofile=testdata/coverage.out .
+    go test -coverprofile=testdata/coverage.out ./...
 
 }
 
